### ISSUE TITLE
怎么设置权限还有查看命令?

### ISSUE THREAD

**Issue by lancer-wang** [Ailitonia/nonebot2_miya#10]
![image](https://user-images.githubusercontent.com/69783837/114641395-a21a6180-9d04-11eb-8168-7b29e82ea4d8.png)
/Omega和/OmegaAuth,都用了
用/help直接会被 命令冷却中!

**Comment by Ailitonia** [comment]
https://github.com/Ailitonia/nonebot2_miya/blob/1c094e7af7c613f9b357e1e40a8a4e02c55ea51e/omega_miya/plugins/Omega_manage/__init__.py#L2-L8

/Omega 命令看上面说明

https://github.com/Ailitonia/nonebot2_miya/blob/1c094e7af7c613f9b357e1e40a8a4e02c55ea51e/omega_miya/plugins/Omega_manage/__init__.py#L116-L117

使用 /Omega Init 时会配置默认权限节点，包括免 /help 命令 cd

https://github.com/Ailitonia/nonebot2_miya/blob/1c094e7af7c613f9b357e1e40a8a4e02c55ea51e/omega_miya/plugins/Omega_auth_manage/__init__.py#L25-L26

/OmegaAuth 命令的 rule 为 to_me，需要私聊或群里@触发，或者自己把这个改掉

**Comment by lancer-wang** [comment]
多谢,没注意这里
