### ISSUE TITLE
运行bot.py时报错：ModuleNotFoundError: No module named 'nonebot'

### ISSUE THREAD

**Issue by Octomouch** [Ailitonia/nonebot2_miya#101]
如标题所说，运行时报错No module named 'nonebot'，
但是通过pip list指令查询可知，nonebot已经安装。
![image](https://user-images.githubusercontent.com/66351932/176661155-97083bc9-fe13-41d9-91d9-ff11bcbf5890.png)
![image](https://user-images.githubusercontent.com/66351932/176661251-2bb4d53d-e421-473a-b942-9490ed325eac.png)
很费解，不知道哪里出了差错。

**Comment by Ailitonia** [comment]
https://github.com/nonebot/discussions/discussions/13#discussioncomment-738461

另外确认：
1. 依赖是在虚拟环境外安装的还是在虚拟环境内安装的
2. 安装时使用的是 `pip` 还是 `pip3`, 运行时使用的是 `python` 还是 `python3`

**Comment by Ailitonia** [comment]
尝试在虚拟环境内使用 pip install 安装依赖
