### ISSUE TITLE
频道内使用指令无效或提示权限不足

### ISSUE THREAD

**Issue by Octomouch** [Ailitonia/nonebot2_miya#103]
如题，部署完成后bot能够**正常回应QQ私聊**，但是**频道内**公屏聊天或者私聊时，使用/Omega Init等指令无响应，
![image](https://user-images.githubusercontent.com/66351932/177028741-3f5ca6e9-5ae5-4e43-afe7-6e31ce67e9db.png)

并且控制台输出如下错误
![image](https://user-images.githubusercontent.com/66351932/177028698-277906ca-3f10-4892-92e1-69d7eb402584.png)

使用**超级管理员账号**@bot并且使用/help指令，会提示权限不足
![image](https://user-images.githubusercontent.com/66351932/177028725-4a3159bc-762a-43d2-8fa8-b136bbdb15f0.png)

同时伴有Denied Entity的报错
![image](https://user-images.githubusercontent.com/66351932/177028892-fd15dd9b-9d96-4459-9267-92528ca3f5fc.png)

很费解，希望大佬有时间能解答一下疑惑

**Comment by Ailitonia** [comment]
`/omega init` 和 `/omega setlevel` 是单独针对每个群/频道/用户的，也就是说你需要在每个你想要启用 bot 功能的群或频道单独进行配置
