### ISSUE TITLE
关于代理问题

### ISSUE THREAD

**Issue by lancer-wang** [Ailitonia/nonebot2_miya#11]
我想看Pixiv日榜,然后发现图片下载失败,
于是我挂了代理,依然失败,这是为什么?是我哪里没有配置吗
![QQ图片20210414152319](https://user-images.githubusercontent.com/69783837/114670318-72d01880-9d35-11eb-8e81-dc266a481b5d.jpg)
![QQ图片20210414152335](https://user-images.githubusercontent.com/69783837/114670319-74014580-9d35-11eb-868d-87281ca6e5d5.jpg)
![QQ图片20210414152338](https://user-images.githubusercontent.com/69783837/114670320-74014580-9d35-11eb-831c-119e9b4c334c.jpg)
![QQ图片20210414152341](https://user-images.githubusercontent.com/69783837/114670323-7499dc00-9d35-11eb-85fc-98da8d7cafa6.jpg)

**Comment by Ailitonia** [comment]
这其实算是个遗留问题😂

以前是不方便使用代理所以 Pixiv 这些需要梯子的插件是通过架设一个放在外网上的 api 获取资源的

https://github.com/Ailitonia/nonebot2_miya/blob/1c094e7af7c613f9b357e1e40a8a4e02c55ea51e/.env.dev#L47-L49

![image](https://user-images.githubusercontent.com/41713304/114695521-5096c480-9d4e-11eb-8149-c26309b5a94b.png)

然后 proxy 组件加入是为了实验性改善B站插件被风控的情况

不过现在刚刚正在重写网络请求的部分，可以把 api 上面 Pixiv 相关的模块重新整合到插件里面了

等我后面更新吧（

**Comment by lancer-wang** [comment]
好的

**Comment by lancer-wang** [comment]
![image](https://user-images.githubusercontent.com/69783837/114807912-db70d100-9dd9-11eb-8adb-2018dd46241a.png)
用api也不行,可能是我这边网络不好吧....

**Comment by Ailitonia** [comment]
已在 #12 解决
