### ISSUE TITLE
这是什么鬼bug

### ISSUE THREAD

**Issue by lancer-wang** [Ailitonia/nonebot2_miya#61]
![image](https://user-images.githubusercontent.com/69783837/137687406-b429f951-aa52-454f-ad56-d4d441c67be6.png)
mysql版本是5.6

**Comment by Ailitonia** [comment]
是不是字符集问题，我这无法复现这个错误

![image](https://user-images.githubusercontent.com/41713304/137951721-6b8aa126-ffd6-41e2-a901-a9625c29936c.png)
![image](https://user-images.githubusercontent.com/41713304/137951744-192baec7-14bb-4bba-b7e2-f3e56299ee0a.png)

pid 81006544
数据库版本 5.5.68-MariaDB
字符集 utf8mb4
